# Generated by Django 3.2.9 on 2021-11-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='position',
            name='img',
            field=models.TextField(),
        ),
    ]
