# Generated by Django 3.2.9 on 2021-11-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project1', '0002_auto_20211127_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.TextField(max_length=200),
        ),
    ]
