# Generated by Django 3.2.9 on 2021-11-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project1', '0003_alter_choice_choice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=6),
        ),
    ]
